### ISSUE TITLE
Orden de operaciones SUB y MOD

### ISSUE THREAD

**Issue by AracnidKnight** [diegocaro/fundcomp#1]
¿Las operaciones no deberían de ser de la forma penúltimo - ultimo, o para MOD penúltimo % ultimo?

Ya que DIV funciona de esa manera es extraño que difieran las demás operaciones, y se puede prestar a confusiones.

Por cierto, soy estudiante suyo profesor ^^.

**Comment by AracnidKnight** [comment]
Esto es en la versión simple del código

**Comment by diegocaro** [comment]
Toda la razón @AracnidKnight! Ya lo corregí. Felicitaciones!

**Comment by AracnidKnight** [comment]
Gracias profe! ¿Aunque SUB debería mantenerse como está?

**Comment by diegocaro** [comment]
En efecto! Creo que te ganaste unas décimas ;)

**Comment by diegocaro** [comment]
Envíame tu nombre a mi correo usach
